CREATE TABLE [dbo].[Tickets]
(
[AssigneeId] [bigint] NULL,
[BrandId] [bigint] NULL,
[CommentId] [bigint] NULL,
[CommentType] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentBody] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentHtmlBody] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentPlainBody] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentPublic] [bit] NULL,
[CommentAuthorId] [bigint] NULL,
[CommentViaChannel] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceFromAddress] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceFromName] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceFromFormattedPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceFromPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceToAddress] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceToName] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceToFormattedPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceToPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CommentViaSourceRel] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[CreatedAt] [datetime] NULL,
[Description] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[DueAt] [datetime] NULL,
[GroupId] [bigint] NULL,
[HasIncidents] [bit] NULL,
[Id] [bigint] NOT NULL,
[IsPublic] [bit] NULL,
[OrganizationId] [bigint] NULL,
[Priority] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Recipient] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[RequesterLocaleId] [bigint] NULL,
[RequesterName] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[RequesterEmail] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[RequesterId] [bigint] NULL,
[SatisfactionRatingScore] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[SatisfactionRatingComment] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Status] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[Subject] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[SubmitterId] [bigint] NULL,
[TicketFormId] [bigint] NULL,
[Type] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[UpdatedAt] [datetime] NULL,
[Url] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaChannel] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceFromAddress] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceFromName] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceFromFormattedPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceFromPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceToAddress] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceToName] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceToFormattedphone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceToPhone] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaSourceRel] [nvarchar] (max) COLLATE Latin1_General_CI_AS NULL,
[ViaFollowupSourceId] [bigint] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tickets] ADD CONSTRAINT [PK_Tickets] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
